name: Build Arduino

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Arduino CI
        uses: Arduino-CI/action@v0.1.6
        env:
          EXPECT_EXAMPLES: true
          EXPECT_UNITTESTS: false